# Global variables
eureka-url: http://localhost:8761

# Eureka registration
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${eureka-url}/eureka
  instance:
    prefer-ip-address: true