spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/music-shop
    username: ${MUSIC_SHOP_DB_USERNAME}
    password: ${MUSIC_SHOP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET}

eureka:
  instance:
    hostname: customer-service

server:
  port: 8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
