spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: gateway

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080
