spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/music-shop
    username: ${MUSIC_SHOP_DB_USERNAME}
    password: ${MUSIC_SHOP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  instance:
    hostname: stock-service

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
